//******************************************************
//Instituto Federal de São Paulo - Campus Sertãozinho
//Disciplina......: M3LPBD
//Programação de Computadores e Dispositivos Móveis
//Aluno...........: JORGE AUGUSTO PEREIRA DE CARVALHO
//******************************************************

package projetomodulo3;

import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ProjetoModulo3Form extends javax.swing.JFrame {

       Vector lista = new Vector();
       BufferedWriter br;
    private Object jComboBox1;
    
    /**
     * Creates new form NomeSobrenomeForm
     */
    
    public ProjetoModulo3Form() {
        initComponents();
           try {
               br = new BufferedWriter (new FileWriter(new File("arquivo_disciplinas.txt")));
           } catch (IOException ex) {
               JOptionPane.showMessageDialog(rootPane, ex.getMessage());
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabelDisciplina = new javax.swing.JLabel();
        jTextFieldDisciplina = new javax.swing.JTextField();
        jLabelCurso = new javax.swing.JLabel();
        jTextFieldCurso = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCargaHora = new javax.swing.JLabel();
        jTextFieldCargaHora = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jLabelHs = new javax.swing.JLabel();
        jLabelVagas = new javax.swing.JLabel();
        jTextFieldVagas = new javax.swing.JTextField();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jLabelTurno = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDisciplina.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDisciplina.setText("Disciplina");

        jLabelCurso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCurso.setText("Curso");

        jButtonCadastrar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCargaHora.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCargaHora.setText("Carga Horaria");

        jTextFieldCargaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargaHoraActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTitulo.setText("Projeto IFSP Modulo 3 - Cadastro de Disciplinas");

        jButtonExcluir.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonExcluir.setText("Excluir cadastrada");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelHs.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelHs.setText("horas");

        jLabelVagas.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelVagas.setText("Nº de Vagas");

        jTextFieldVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVagasActionPerformed(evt);
            }
        });

        jComboBoxTurno.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        jComboBoxTurno.setToolTipText("Turno");
        jComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTurnoActionPerformed(evt);
            }
        });

        jLabelTurno.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelTurno.setText("Turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDisciplina)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCargaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelHs))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabelTitulo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDisciplina, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCurso)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCargaHora))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonExcluir)
                                    .addComponent(jLabelVagas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTurno))
                                .addGap(35, 35, 35)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(13, 13, 13)
                .addComponent(jLabelDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCargaHora)
                    .addComponent(jLabelVagas)
                    .addComponent(jLabelTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCargaHora)
                        .addComponent(jLabelHs))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldVagas)
                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
//******************************************************
//******************************************************
// CONFIGURAÇÃO DO jBUTTON PARA CADASTRAR
    // com jOptionPane
//******************************************************
//******************************************************
    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
     try {   
        String cmd = "insert into disciplinas ( idDisciplinas, idCurso, horasAula, vagas, turno) VALUES ('"+jTextFieldDisciplina.getText()+"','"+jTextFieldCurso.getText()+"','"+jTextFieldCargaHora.getText()+"','"+jTextFieldVagas.getText()+"', '"+jComboBoxTurno.getSelectedItem()+"')" ;
        Connection con = ConexaoMySQL.getInstance().getConnection();
        con.createStatement().executeUpdate(cmd);             
          } catch (SQLException ex) {
               ex.printStackTrace();
           }
        
        Cadastro p = new Cadastro();
        if (jTextFieldDisciplina.getText().isEmpty() || jTextFieldCurso.getText().isEmpty() || jTextFieldCargaHora.getText().isEmpty() || jTextFieldVagas.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "o usuário deve preencher todos os campos!", "ERRO DE UTILIZAÇÃO", JOptionPane.ERROR_MESSAGE);
        }else{
            String msg = "Disciplina: " + jTextFieldDisciplina.getText() +  "  Cadastrada!";
            JOptionPane.showMessageDialog(rootPane, msg, "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            p.setDisciplina(jTextFieldDisciplina.getText());
            p.setCurso(jTextFieldCurso.getText());
            int horas = Integer.parseInt(jTextFieldCargaHora.getText());
            p.setHoras(horas);
            int vagas = Integer.parseInt(jTextFieldVagas.getText());
            p.setVagas(vagas);
            p.setTurno((String) jComboBoxTurno.getSelectedItem());
            
            lista.add(p);
            try {
                br.write(p.toString());
                br.flush();
                br.newLine();
                
                
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }

        }
        System.out.println(lista);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldCargaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargaHoraActionPerformed

    private void jTextFieldVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVagasActionPerformed

    
//******************************************************
//******************************************************
// CONFIGURAÇÃO DO jBUTTON PARA ABRIR NOVA JANELA DE EXCLUIR CADASTRADOS
//******************************************************
//******************************************************
    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
    
      this.dispose();
      ExcluirCadastro botao = new ExcluirCadastro();
      botao.setVisible(true);
            
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoModulo3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoModulo3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoModulo3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoModulo3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoModulo3Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabelCargaHora;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelDisciplina;
    private javax.swing.JLabel jLabelHs;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JLabel jLabelVagas;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCargaHora;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldDisciplina;
    private javax.swing.JTextField jTextFieldVagas;
    // End of variables declaration//GEN-END:variables

 

    private static class string {

        public string() {
        }
    }


}
